version: "3"

services:
  master:
    build: .
    ports:
      - "50070:50070"
      - "9000:9000"
      - "8025:8025"
      - "8035:8035"
      - "8050:8050"
      - "2122:22"
    command: bash -c "/root/boot_master.sh && /usr/bin/supervisord -c /etc/supervisor/supervisord-master.conf"
    extra_hosts:
      - "hadoop-master:192.168.1.2"
      - "hadoop-slave1:192.168.1.3"
      - "hadoop-slave2:192.168.1.4"
      - "hadoop-slave3:192.168.1.5"
      - "hadoop-slave4:192.168.1.6"

  slave:
    build: .
    ports:
      - "50075:50075"
      - "2120:2120"
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord-slave.conf
    extra_hosts:
      - "hadoop-master:192.168.1.2"
      - "hadoop-slave1:192.168.1.3"
      - "hadoop-slave2:192.168.1.4"
      - "hadoop-slave3:192.168.1.5"
      - "hadoop-slave4:192.168.1.6"
